reference_fasta: "data/v95.fna"
ref_prefix: "votu"
output_prefix: "votu_bulk"

num_samples: 109
sample_prefix: "TLL" # sample prefix
padding: 1 # number of digits to pad sample numbers

reads_dir: "data/reads/"
reads_r1: ".1.fastq.gz"
reads_r2: ".2.fastq.gz"

min_id: 95
min_cov: 80
check_proper_pair: 1
covthresh: 70
